language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: live
before_script:
  - "yarn global add gatsby"
  - "yarn install"
script:
  - "npm run test"
after_success:
  - "yarn deploy"
