language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
before_install:
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib && haxelib -notimeout setup ~/haxelib
  - haxelib -notimeout install lime > /dev/null
  - haxelib -notimeout install openfl
  - haxelib -notimeout install flixel
  - haxelib -notimeout run lime setup flixel > /dev/null
before_script:
  - "yarn global add gatsby"
  - "yarn install"
script:
  - "npm run test"
after_success:
  - "yarn build"
