language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only:
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
before_script:
  - "yarn global add gatsby"
  - "yarn install"
script:
  - "npm run test"
after_success:
  - "yarn build"
