#+TITLE: ALIEN, e x p a n s i o n .
#+ICON: game/favicon.png
#+ICON_MODE: pixelated
#+ICON_TYPE: normal
#+TYPE: game
#+LANG: pico
#+PLACEHOLDER: game/placeholder.png
#+LANDSCAPE: nil
#+GAME: game/index.js
#+LUDUM_DARE: 44/alien-e-x-p-a-n-s-i-o-n

** Instructions

Play as an alien bounty hunter attempting to amass a small fortune by capturing human manned ships using a state-of-the-art vortex laser.

You will be payed by some of the galaxies top scientists who aim to study these humans.

Be careful as hitting human ships will deplete your life meter and more importantly will lead to unwarranted attention and hence will detract from your score/pay.

However capturing a human will restore a small amount of life and the increase your score.  Additionally flying past human ships will also add to your score.

Capture as many ships as possible to achieve a high payday and satisfy the scientists.
*** Controls

- *Arrows Keys* - Control your ship
- *X Key* - Fire vortex laser / Advance menus
- *Z Key* - Change camera settings (menu)
*** About

Small game created in under 48 hours for [[https://ldjam.com/events/ludum-dare/44][Ludum Dare 44]] with the theme of *Your life is currency*.

Game is built using [[https://www.lua.org/][Lua]] and [[https://moonscript.org/][MoonScript]], with the [[https://www.lexaloffle.com/pico-8.php][PICO-8]] Fantasy Console.

Entered as a [[https://ldjam.com/events/ludum-dare/44][Ludum Dare 44]] *compo* game.
