name: build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.9'
        registry-url: 'https://registry.npmjs.org'
    - name: Deploy Info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Test
      run: yarn test
    - name: Generate Version
      run: |
        echo "VERSION=$(./version.sh)" >> $GITHUB_ENV
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: master
        folder: public
        commit-message: ${{ env.VERSION }}
