name: build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: './.nvmrc'
        registry-url: 'https://registry.npmjs.org'
    - name: use pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: ./package.json
    - name: Install
      run: pnpm install
    - name: Build
      run: pnpm build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Test
      run: pnpm test
    - name: Generate Version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "VERSION=$(./version.sh)" >> $GITHUB_ENV
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        branch: master
        folder: out
        commit-message: ${{ env.VERSION }}
